### PR TITLE
PSR2 compliance

### PR DESCRIPTION
**Pull request by charlycoste**
Complying to [PSR2 conventions](http://www.php-fig.org/psr/psr-2/)

Just in case...

### CODE REVIEW

**Comment by amouhzi** [comment]
Thank you for your contribution. I like me too to follow conventions.

**Comment by charlycoste** [comment]
You're welcome ;)

**Comment by charlycoste** [comment]
Sorry, but I realized that by adding

    script:
    - ./vendor/bin/phpcs --warning-severity=0 --standard=PSR2 src

to your .travis.yml file, I overrided the default phpunit run

So you would propably prefer to add : 

    script:
    - ./vendor/bin/phpcs --warning-severity=0 --standard=PSR2 src
    - phpunit

**Comment by amouhzi** [comment]
Many thanks, I didn't noticed that.

**Pull request merged**
