### PR TITLE
PHP Doc cleanup

### PR DESCRIPTION
**Pull request by nadar**
+ Remove boolean typo
+ Use boolean instead of bool for all phpdoc types
+ Fixed variable description
+ Removed symfony coding standard annotation.

### CODE REVIEW

**Comment by nadar** [comment]
@amouhzi any news on this?

**Comment by nadar** [comment]
@amouhzi Is there something to change? cause the typos should be fixed...

**Comment by nadar** [comment]
@amouhzi done

**Comment by amouhzi** [comment]
Thank you :-)

**Pull request merged**
