### PR TITLE
Fixed broken User Agent Link.

### PR DESCRIPTION
**Pull request by nadar**

### CODE REVIEW

**Comment by amouhzi** [comment]
Thank you.

**Comment by nadar** [comment]
Maybe the Version 1.5 should be switched to 1.6.

**Comment by amouhzi** [comment]
No, as this does not affect the code working.

**Comment by nadar** [comment]
I ment: https://github.com/php-mod/curl/blob/master/src/Curl/Curl.php#L69

should be `'PHP Curl/1.6 ...` instead of `'PHP Curl/1.5  ....`

**Comment by nadar** [comment]
Or its not related to this librarys version?

**Comment by amouhzi** [comment]
Yes you're right. it is related.

**Comment by amouhzi** [comment]
I fixed it. thanks.

**Pull request merged**
