### PR TITLE
add CURLOPT_CUSTOMREQUEST for get/post function

### PR DESCRIPTION
**Pull request by mean-cj**

### CODE REVIEW

**Comment by nadar** [comment]
Hi @mean-cj 

Whats to benefit of introducing this? What does it change? Could you please elaborate?

**Comment by mean-cj** [comment]
Hi nada

When we need to call $curl->get() after $curl->post() , 
curl option "CURLOPT_CUSTOMREQUEST" doesn't  work because curl option remember CURLOPT_CUSTOMREQUEST = POST

fixed
add $this->setOpt(CURLOPT_CUSTOMREQUEST, "GET"); into the get method.

**Review by nadar — APPROVED** [review]
But then you should create two objects any how. That old code design of this project is somewhat outdated and the response should be immutable or stored in separate object, but its not. So i would recommend:

```
$get = (new Curl())->get(...)
$post = (new Curl())->post(...)
```

But since we set customrequest also for put, patch, delete, this looks good to me.

**Comment by nadar** [comment]
> When you change the request method by setting [CURLOPT_CUSTOMREQUEST](https://curl.se/libcurl/c/CURLOPT_CUSTOMREQUEST.html) to something, you do not actually change how libcurl behaves or acts in regards to the particular request method, it will only change the actual string sent in the request.

**Pull request merged**
