### PR TITLE
Added PHPDocs

### LINKED ISSUE #18: Add PHPDoc-Documentation
Can you please add PHPDoc-Documentation.

Thank you.

### PR DESCRIPTION
**Pull request by nadar**
Improvments:
+ added basic phpdocs
+ udpate readme
+ add files to ignore list
+ used php-cs-fixer

Changes:
+ marked `setReferrer` as deprecated but added `setReferer`

Questions:
+ I was not able to make local testings, maybe adding a guide, or refractor the testing suite, as its seems a bit outdated.
+ Add version informations for deprecated methods, e.g. lets say `will be removed in 2.0.0` and then removed them as well in version 2.0.0 ;-)

closes #18

### CODE REVIEW

**Comment by nadar** [comment]
So as i already sad, i need inputs in how to enable unit testing or how to fix, or refactoring the unit tests. If the testings are enabled we should add the build badge from travis as well enabling https://coveralls.io service and provide informations. This would provide more and better informations about unit tests when deailing with pull requests.

**Comment by amouhzi** [comment]
To run tests locally, you need a web server configured like as I did for travis:

  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

Apache Configuration:

```
<VirtualHost` *:80>
  DocumentRoot %TRAVIS_BUILD_DIR%/tests/server/php-curl-test

  <Directory "%TRAVIS_BUILD_DIR%">
    Options FollowSymLinks MultiViews ExecCGI
    AllowOverride All
    Order deny,allow
    Allow from all
  </Directory>

  # Wire up Apache to use Travis CI's php-fpm.
  <IfModule mod_fastcgi.c>
    AddHandler php5-fcgi .php
    Action php5-fcgi /php5-fcgi
    Alias /php5-fcgi /usr/lib/cgi-bin/php5-fcgi
    FastCgiExternalServer /usr/lib/cgi-bin/php5-fcgi -host 127.0.0.1:9000 -pass-header Authorization
  </IfModule>
</VirtualHost>
```

You can use nginx if you know how.

Juste make sure the virtual host points to `/tests/server/php-curl-test` as a root directory.
And update `const TEST_URL = 'http://localhost';` to use your locally host.

**Comment by nadar** [comment]
Only php7 seems to fail now.
https://travis-ci.org/php-mod/curl/builds/184744220

The unit test description should be part of the README.md:
https://github.com/nadar/curl/blob/1ec71d2285168e8c379a94bb0b328410af3e70d9/README.md#testing

**Comment by amouhzi** [comment]
.travis-ci.yml is not adapted for php7 yet.

**Pull request merged**
